# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]


  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  job1:
    # The type of runner that the job will run on
    runs-on: macos-11.0
    steps:
      - name: Show date
        run: date -j -vJulm -v20d -v1999y '+%A'
  job2:
    runs-on: ubuntu-latest
    steps:
      - name: Print Date
        run: date
  job3:
    runs-on: windows-latest
    steps:
      - name: Print Date
        run: "Date"
  job4:
    runs-on: ubuntu-latest
    needs: [jobq, job2, job3]
    steps:
      - name: Show date
        run: date
